export const GET_TRENDING_PRODUCT_REQUEST = "GET_TRENDING_PRODUCT_REQUEST";
export const GET_TRENDING_PRODUCT_SUCCESS = "GET_TRENDING_PRODUCT_SUCCESS";
export const GET_TRENDING_PRODUCT_FAIL = "GET_TRENDING_PRODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
